config/routes.rb
Rails.application.routes.draw do
  
  root "main#index"

   resources :creatures

  

 

end

app/models/creature.rb
class Creature < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  def index
    @creatures = Creature.all
  end

  def create
    Creature.create creature_params
    redirect_to creatures_path
  end

  def new
    @creature = Creature.new
  end

  def edit
    @creature = Creature.find params[:id]
  end

  def show
    @creature = Creature.find params[:id]
  end

  def update
    c = Creature.find params[:id]
    c.update creature_params
    redirect_to creatures_path
  end

  def destroy
    @c = Creature.find params[:id]
    @c.delete
    redirect_to creatures_path
  end

  private

  def creature_params
    params.require(:creature).permit(:name, :description)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/creatures/edit.html.erb
<h1>Creatures#edit</h1>
<p>Find me in app/views/creatures/edit.html.erb</p>

<%= bootstrap_form_for @creature do |c| %>
	
	<%= c.text_field :name %>
	<%= c.text_field :description %>

	<%= c.primary %>

<% end %>

app/views/creatures/index.html.erb
<h1>Creatures#index</h1>
<p>Find me in app/views/creatures/index.html.erb</p>

<% @creatures.each do |c| %>

	<div class="well">
		<h2>Name: <%= c.name %></h2>
		<p>Description: <%= c.description %></p>

		<%= link_to "Edit", edit_creature_path(c), class: "btn btn-primary" %>
		<%= link_to "Delete", c, method: :delete, class: "btn btn-danger" %>
	</div>

<% end %>

app/views/creatures/new.html.erb
<h1>Creatures#new</h1>
<p>Find me in app/views/creatures/new.html.erb</p>

<h1>Create new creature</h1>

<%= bootstrap_form_for @creature do |c| %>
	<%= c.text_field :name %>
	<%= c.text_field :description %>

	<%= c.primary %>
<% end %>

app/views/creatures/show.html.erb
<h1>Creatures#show</h1>
<p>Find me in app/views/creatures/show.html.erb</p>

<div class="well">
	<h2><%= @creature.name %></h2>
	<p><%= @creature.description %></p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BogApp</title>
  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

	<nav class="navbar navbar-default" role="navigation">

	<div class="navbar-header">		
		<a class="navbar-brand" href="/">Home page</a>
	</div>

	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav">
			<li class="active"><a href="/creatures/new">Creature creatures</a></li>
			<li><a href="/creatures">List creature</a></li>
		</ul>
	</nav>
	
	<%= yield %>	
</div>

</body>
</html>

app/views/main/index.html.erb
<h1>Welcome to bogs</h1>